apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: test7
  namespace: test7
spec:
  repo:
    replicas: 3
  server:
    replicas: 3
    route:
      enabled: true
      path: /
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: passthrough
      wildcardPolicy: None
